server:
  port: {$SPRING_MAIL_SERVER_PORT:8080}

spring:
  mail:
    host: ${SPRING_MAIL_HOST:smtp.gmail.com}
    username: ${SPRING_MAIL_USERNAME:}
    password: ${SPRING_MAIL_PASSWORD:}
    properties:
      mail:
        transport:
          protocol: ${SPRING_MAIL_PROPERTIES_MAIL_TRANSPORT_PROTOCOL:smtp}
        smtp:
          port: ${SPRING_MAIL_PROPERTIES_MAIL_SMTP_PORT:587} # 587 - gmail
          auth: ${SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH:true}
          startttls:
            enable: ${SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE:true}
            required: ${SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_REQUIRED:true}
    debug: true